// Generated by CoffeeScript 1.3.3
(function() {

  Ext.define("DriversLog.view.LogsList", {
    extend: "Ext.Panel",
    alias: "widget.logslist",
    config: {
      scrollable: true,
      items: []
    }
  });

}).call(this);
