// Generated by CoffeeScript 1.3.3

/**
 * @class DriversLog.view.Logs
 * @extends Ext.Panel
 * View (Container) to list logs and add new ones
*/


(function() {

  Ext.define('DriversLog.view.LogsView', {
    extend: 'Ext.Panel',
    alias: 'widget.logsview',
    config: {
      title: "Driver's Log",
      iconCls: "speedometer",
      items: [
        {
          docked: "top",
          xtype: "titlebar",
          title: "Driver's Log",
          items: [
            {
              xtype: "button",
              ui: "action",
              iconCls: "add",
              align: "right",
              iconMask: true,
              itemId: "addLogEntryButton"
            }
          ]
        }
      ],
      listeners: [
        {
          delegate: "#addLogEntryButton",
          event: "tap",
          fn: function() {
            return this.fireEvent("addLogEntryCommand");
          }
        }
      ]
    }
  });

}).call(this);
