// Generated by CoffeeScript 1.3.3
(function() {

  Ext.define("DriversLog.view.Main", {
    extend: "Ext.TabPanel",
    alias: "widget.mainview",
    requires: ["Ext.TitleBar"],
    config: {
      layout: {
        type: "fit"
      },
      tabBarPosition: "bottom",
      items: [
        {
          xtype: "logslist"
        }, {
          title: "more"
        }
      ]
    }
  });

}).call(this);
