// Generated by CoffeeScript 1.3.3
(function() {

  Ext.define("DiversLog.view.Main", {
    extend: "Ext.tab.Panel",
    alias: "widget.mainView",
    requires: ["Ext.TitleBar"],
    onAddLogEntryTap: function() {
      return console.log("test");
    },
    config: {
      tabBarPosition: "bottom",
      items: [
        {
          title: "Driver's Log",
          iconCls: "speedometer",
          scrollable: true,
          items: [
            {
              docked: "top",
              xtype: "titlebar",
              title: "Driver's Log",
              items: [
                {
                  xtype: "button",
                  ui: "action",
                  iconCls: "add",
                  align: "right",
                  iconMask: true,
                  itemId: "addNoteButton"
                }
              ]
            }
          ]
        }
      ],
      listeners: [
        {
          delegate: "#addNoteButton",
          event: "tap",
          fn: "onAddLogEntryTap"
        }
      ]
    }
  });

}).call(this);
