// Generated by CoffeeScript 1.3.3
(function() {

  Ext.define("DriversLog.controller.Logs", {
    extend: "Ext.app.Controller",
    config: {
      refs: {
        mainView: "mainview"
      },
      control: {
        mainView: {
          addLogEntryCommand: "onAddLogEntryCommand"
        }
      }
    },
    onAddLogEntryCommand: function() {
      return console.log("add log entry");
    }
  });

}).call(this);
