// Generated by CoffeeScript 1.3.3
(function() {

  Ext.define("DriversLog.controller.Logs", {
    extend: "Ext.app.Controller",
    config: {
      refs: {
        mainView: "mainview",
        logEditor: "logeditor"
      },
      control: {
        mainView: {
          addLogEntryCommand: "onAddLogEntryCommand"
        }
      }
    },
    slideLeftTransition: {
      type: 'slide',
      direction: 'left'
    },
    slideRightTransition: {
      type: 'slide',
      direction: 'right'
    },
    onAddLogEntryCommand: function() {
      Ext.Viewport.animateActiveItem(this.getLogEditor(), this.slideLeftTransition);
      return console.log("add log entry");
    }
  });

}).call(this);
